"""add triggered by

Revision ID: 1153ceb39699
Revises: 2301decfc815
Create Date: 2019-10-15 09:13:58.110613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1153ceb39699'
down_revision = '2301decfc815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_histories', sa.Column('triggered_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_histories', 'triggered_by')
    # ### end Alembic commands ###
