"""delete triggered by

Revision ID: 2301decfc815
Revises: 458fde5ec6fa
Create Date: 2019-10-15 09:12:49.785092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2301decfc815'
down_revision = '458fde5ec6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_histories', 'triggered_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_histories', sa.Column('triggered_by', mysql.ENUM('ML', 'User'), nullable=True))
    # ### end Alembic commands ###
