"""add parent_id to users

Revision ID: 75a1b0ca300f
Revises: 526599a0a109
Create Date: 2019-10-12 14:29:06.089414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a1b0ca300f'
down_revision = '526599a0a109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parent_id')
    # ### end Alembic commands ###
