"""empty message

Revision ID: 7f9d1a13d4f0
Revises: 0b5daa0362ae
Create Date: 2019-10-04 23:03:33.840863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f9d1a13d4f0'
down_revision = '0b5daa0362ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('datasets', sa.Column('days', sa.Enum('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', name='days_enum'), nullable=True))
    op.add_column('datasets', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('time_minutes', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('weather', sa.Enum('Sunny', 'Cloudy', 'Rainy', 'Windy', 'Snowy', name='weather_enum'), nullable=True))
    op.drop_constraint('datasets_ibfk_2', 'datasets', type_='foreignkey')
    op.create_foreign_key(None, 'datasets', 'devices', ['device_id'], ['id'])
    op.drop_column('datasets', 'user_id')
    op.add_column('power_expenses', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('power_expenses_ibfk_1', 'power_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'power_expenses', 'devices', ['device_id'], ['id'])
    op.drop_column('power_expenses', 'user_id')
    op.add_column('power_usages', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('power_usages', sa.Column('time_minutes', sa.Integer(), nullable=True))
    op.drop_constraint('power_usages_ibfk_2', 'power_usages', type_='foreignkey')
    op.create_foreign_key(None, 'power_usages', 'devices', ['device_id'], ['id'])
    op.drop_column('power_usages', 'user_id')
    op.add_column('switches', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('switches_ibfk_1', 'switches', type_='foreignkey')
    op.create_foreign_key(None, 'switches', 'devices', ['device_id'], ['id'])
    op.drop_column('switches', 'user_id')
    op.add_column('usage_histories', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('usage_histories', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('usage_histories', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_constraint('usage_histories_ibfk_2', 'usage_histories', type_='foreignkey')
    op.create_foreign_key(None, 'usage_histories', 'devices', ['device_id'], ['id'])
    op.drop_column('usage_histories', 'user_id')
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=True))
    op.drop_column('users', 'serial_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('serial_number', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'city')
    op.add_column('usage_histories', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usage_histories', type_='foreignkey')
    op.create_foreign_key('usage_histories_ibfk_2', 'usage_histories', 'users', ['user_id'], ['id'])
    op.drop_column('usage_histories', 'status')
    op.drop_column('usage_histories', 'duration')
    op.drop_column('usage_histories', 'device_id')
    op.add_column('switches', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'switches', type_='foreignkey')
    op.create_foreign_key('switches_ibfk_1', 'switches', 'users', ['user_id'], ['id'])
    op.drop_column('switches', 'device_id')
    op.add_column('power_usages', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'power_usages', type_='foreignkey')
    op.create_foreign_key('power_usages_ibfk_2', 'power_usages', 'users', ['user_id'], ['id'])
    op.drop_column('power_usages', 'time_minutes')
    op.drop_column('power_usages', 'device_id')
    op.add_column('power_expenses', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'power_expenses', type_='foreignkey')
    op.create_foreign_key('power_expenses_ibfk_1', 'power_expenses', 'users', ['user_id'], ['id'])
    op.drop_column('power_expenses', 'device_id')
    op.add_column('datasets', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.create_foreign_key('datasets_ibfk_2', 'datasets', 'users', ['user_id'], ['id'])
    op.drop_column('datasets', 'weather')
    op.drop_column('datasets', 'time_minutes')
    op.drop_column('datasets', 'device_id')
    op.drop_column('datasets', 'days')
    op.drop_table('devices')
    # ### end Alembic commands ###
