"""add timestamp

Revision ID: 8678f7f75bf8
Revises: b5b687d9387e
Create Date: 2019-10-15 09:42:33.902652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8678f7f75bf8'
down_revision = 'b5b687d9387e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('datasets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('power_expenses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('power_expenses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('power_usages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('power_usages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('switches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('switches', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usage_histories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('usage_histories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('usage_histories', 'updated_at')
    op.drop_column('usage_histories', 'created_at')
    op.drop_column('switches', 'updated_at')
    op.drop_column('switches', 'created_at')
    op.drop_column('power_usages', 'updated_at')
    op.drop_column('power_usages', 'created_at')
    op.drop_column('power_expenses', 'updated_at')
    op.drop_column('power_expenses', 'created_at')
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'created_at')
    op.drop_column('datasets', 'updated_at')
    op.drop_column('datasets', 'created_at')
    # ### end Alembic commands ###
