"""delete triggered by

Revision ID: a7c2ef77d03d
Revises: 1153ceb39699
Create Date: 2019-10-15 09:33:19.134526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7c2ef77d03d'
down_revision = '1153ceb39699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switches', 'triggered_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('triggered_by', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
