"""add triggered by

Revision ID: eeb19c4ea83b
Revises: a7c2ef77d03d
Create Date: 2019-10-15 09:33:43.540432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb19c4ea83b'
down_revision = 'a7c2ef77d03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('triggered_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switches', 'triggered_by')
    # ### end Alembic commands ###
